import {
  BusinessProfile,
  Course,
  CommunityPost,
  Product,
  Mentor,
  ProgramOpportunity,
  UserProfile,
} from '@/lib/types';

export const INITIAL_USER: UserProfile = {
  id: 'usr-001',
  email: 'budi.santoso@sambalkencana.id',
  fullName: 'Budi Santoso, S.T.',
  phone: '081298765432',
  role: 'UMKM_OWNER',
  organizations: [
    { orgId: 'org-kadin-jabar', orgName: 'KADIN Jawa Barat', role: 'UMKM_OWNER' },
    { orgId: 'org-komunitas-bekasi', orgName: 'Komunitas UMKM Naik Kelas Bekasi', role: 'UMKM_OWNER' },
  ],
  createdAt: '2025-01-10T08:00:00Z',
};

export const INITIAL_BUSINESS: BusinessProfile = {
  id: 'biz-001',
  ownerId: 'usr-001',
  ownerName: 'Budi Santoso',
  businessName: 'Sambal Roa Kencana Nusantara',
  category: 'Kuliner',
  subcategory: 'Olahan Pangan & Sambal Kemasan',
  description: 'Produsen sambal roa asap autentik khas Manado dengan rempah Nusantara pilihan, diproduksi higienis dengan kemasan botol kaca kedap udara tahan 6 bulan.',
  foundedYear: 2022,
  province: 'Jawa Barat',
  city: 'Kota Bekasi',
  address: 'Jl. Ahmad Yani No. 88, Margajaya, Bekasi Selatan',
  phone: '021-88997766',
  email: 'halo@sambalkencana.id',
  website: 'https://sambalkencana.id',
  instagram: '@sambalkencana.id',
  whatsapp: '6281298765432',
  employeesCount: 6,
  revenueRange: '50-300 Juta',
  digitalizationLevel: 'Go Digital Aktif',
  certification: {
    nib: true,
    halal: true,
    pirtOrBpom: true,
    haki: false,
    isoOrSni: false,
  },
  marketplacePresence: {
    shopee: true,
    tokopedia: true,
    tiktokShop: true,
    websiteSendiri: true,
    inaMarket: true,
  },
  exportReadiness: 'Potensi Ekspor',
  growthScore: 78,
  growthLevel: 'Naik Kelas',
};

export const INITIAL_COURSES: Course[] = [
  {
    id: 'crs-01',
    title: 'Digitalisasi Bisnis UMKM: Dari Tradisional ke Go Digital',
    category: 'Digitalisasi',
    level: 'Pemula',
    instructor: 'Ir. Hendra Wijaya',
    instructorRole: 'Head of Digital MSME KADIN',
    duration: '2.5 Jam',
    xpReward: 150,
    lessonsCount: 6,
    thumbnail: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=600&auto=format&fit=crop&q=80',
    description: 'Panduan langkah demi langkah memodernisasi tata kelola operasional, sistem kasir POS, dan arsip digital usaha Anda.',
    enrolled: true,
    progress: 100,
    certificateEarned: true,
    curriculum: [
      { title: 'Mengapa UMKM Harus Go Digital?', duration: '15 Menit', completed: true },
      { title: 'Menata Inventori & Kasir Menggunakan Aplikasi POS', duration: '25 Menit', completed: true },
      { title: 'Pembayaran Digital: Implementasi QRIS Nasional', duration: '20 Menit', completed: true },
      { title: 'Evaluasi Efisiensi Biaya Operasional Digital', duration: '30 Menit', completed: true },
    ],
    quiz: [
      {
        question: 'Apa manfaat utama implementasi QRIS bagi pelaku UMKM mikro?',
        options: [
          'Mempermudah pencatatan transaksi non-tunai dan memperluas penerimaan semua e-wallet/perbankan',
          'Menghilangkan kewajiban membayar pajak usaha',
          'Menggantikan fungsi sertifikasi legalitas usaha',
          'Menaikkan harga barang secara otomatis',
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: 'crs-02',
    title: 'Marketing Digital Praktis: Banjir Order via Media Sosial',
    category: 'Pemasaran',
    level: 'Menengah',
    instructor: 'Rina Kartika, M.Mkt',
    instructorRole: 'Senior Growth Strategist & Digital Creator',
    duration: '3 Jam',
    xpReward: 200,
    lessonsCount: 8,
    thumbnail: 'https://images.unsplash.com/photo-1533750516457-a7f992034fec?w=600&auto=format&fit=crop&q=80',
    description: 'Strategi praktis pembuatan konten video pendek di TikTok/Instagram Reels untuk mendatangkan traffic organik dan konversi ke WhatsApp.',
    enrolled: true,
    progress: 60,
    certificateEarned: false,
    curriculum: [
      { title: 'Membedah Algoritma Reels & TikTok untuk Produk UMKM', duration: '25 Menit', completed: true },
      { title: 'Teknik Hook 3 Detik Pertama yang Memikat Penonton', duration: '30 Menit', completed: true },
      { title: 'Mengelola WhatsApp Business untuk Closing Cepat', duration: '35 Menit', completed: true },
      { title: 'Iklan Berbayar Murah: Meta Ads Budget Rp25rb/hari', duration: '40 Menit', completed: false },
    ],
    quiz: [
      {
        question: 'Faktor apa yang paling menentukan keberhasilan video produk di TikTok?',
        options: [
          'Kamera bioskop yang sangat mahal',
          'Daya pikat 3 detik pertama (Hook) dan relevansi cerita manfaat produk bagi audiens',
          'Durasi video minimal 10 menit',
          'Menggunakan bahasa Inggris formal',
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'crs-03',
    title: 'Manajemen Arus Kas & Keuangan UMKM Bebas Boncos',
    category: 'Keuangan',
    level: 'Pemula',
    instructor: 'Ahmad Fauzi, Ak., CA',
    instructorRole: 'Konsultan Keuangan UMKM Terdaftar',
    duration: '2 Jam',
    xpReward: 180,
    lessonsCount: 5,
    thumbnail: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    description: 'Cara memisahkan uang pribadi dengan uang usaha, menghitung HPP akurat, dan merancang proyeksi cash flow yang sehat.',
    enrolled: false,
    progress: 0,
    certificateEarned: false,
    curriculum: [
      { title: 'Prinsip Disiplin Pemisahan Rekening Bisnis & Dompet Pribadi', duration: '20 Menit' },
      { title: 'Rumus Menghitung HPP Produk Kuliner & Manufaktur', duration: '35 Menit' },
      { title: 'Membaca Laporan Laba Rugi Sederhana Setiap Akhir Bulan', duration: '25 Menit' },
    ],
    quiz: [
      {
        question: 'Mengapa mencampurkan uang kas bisnis dengan rekening pribadi berbahaya bagi UMKM?',
        options: [
          'Membuat pemilik tidak tahu laba sebenarnya dan berisiko modal usaha terpakai untuk konsumsi pribadi',
          'Menyebabkan aplikasi bank error',
          'Dilarang oleh undang-undang kepolisian',
          'Hanya boleh dilakukan oleh korporasi besar',
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: 'crs-04',
    title: 'Strategi Tembus Pasar Ekspor & Sertifikasi Global',
    category: 'Ekspor',
    level: 'Lanjutan',
    instructor: 'Dra. Dewi Anggraeni',
    instructorRole: 'Praktisi Ekspor & Komite Hubungan Luar Negeri KADIN',
    duration: '4 Jam',
    xpReward: 300,
    lessonsCount: 10,
    thumbnail: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=600&auto=format&fit=crop&q=80',
    description: 'Persyaratan regulasi ekspor, kemasan standar ekspor, penentuan HS Code, dan cara negosiasi Letter of Credit (L/C) dengan buyer asing.',
    enrolled: false,
    progress: 0,
    certificateEarned: false,
    curriculum: [
      { title: 'Audit Kesiapan Internal: Kapasitas & Standar Mutu', duration: '30 Menit' },
      { title: 'Mencari Data Permintaan Produk di Portal Trade Map ITC', duration: '40 Menit' },
      { title: 'Packaging & Pelabelan Sesuai Regulasi FDA / Uni Eropa', duration: '45 Menit' },
    ],
    quiz: [
      {
        question: 'Apa fungsi dari HS Code (Harmonized System) dalam transaksi ekspor?',
        options: [
          'Kode identifikasi internasional barang untuk menentukan klasifikasi tarif bea masuk dan regulasi impor negara tujuan',
          'Nomor telepon kantor perwakilan dagang',
          'Kode voucher potongan diskon kurir',
          'Nomor rekening bank buyer internasional',
        ],
        correctIndex: 0,
      },
    ],
  },
];

export const INITIAL_POSTS: CommunityPost[] = [
  {
    id: 'post-01',
    authorId: 'usr-901',
    authorName: 'Siti Rahmawati',
    authorBusiness: 'Dapur Keripik Tempe Barokah',
    authorRole: 'UMKM_OWNER',
    category: 'Tips Bisnis',
    title: 'Pengalaman Lolos Audit Sertifikasi Halal SEHATI Tanpa Biaya',
    content: 'Alhamdulillah pekan lalu sertifikat halal BPJPH kami sudah resmi terbit melalui jalur self-declare SEHATI! Kuncinya: pastikan seluruh bumbu dapur dan minyak goreng yang digunakan sudah memiliki nomor sertifikat halal yang valid di database Sihalal. Semoga teman-teman pejuang kuliner segera menyusul!',
    likesCount: 38,
    commentsCount: 14,
    isLiked: true,
    isBookmarked: true,
    createdAt: '2026-09-10T14:20:00Z',
    tags: ['SertifikasiHalal', 'Kuliner', 'SEHATI', 'Legalitas'],
  },
  {
    id: 'post-02',
    authorId: 'usr-902',
    authorName: 'Hadi Prasetyo',
    authorBusiness: 'Batik Tulis Pesona Solo',
    authorRole: 'UMKM_OWNER',
    category: 'Success Story',
    title: 'Dari Penjualan Konvensional ke Order B2B Hotel via INAMarket',
    content: 'Dua bulan lalu saya mulai merapikan katalog digital B2B di INAMarket atas rekomendasi INA AI. Minggu ini kami menandatangani kontrak penyediaan seragam batik 350 potong untuk jaringan hotel di Jawa Tengah. Terima kasih ekosistem KADIN dan UMKM Naik Kelas!',
    likesCount: 64,
    commentsCount: 22,
    isLiked: false,
    isBookmarked: false,
    createdAt: '2026-09-08T09:15:00Z',
    tags: ['INAMarket', 'B2B', 'FashionBatik', 'NaikKelas'],
  },
  {
    id: 'post-03',
    authorId: 'usr-903',
    authorName: 'Dr. Bambang Sutrisno',
    authorBusiness: 'Komite Akses Pembiayaan KADIN',
    authorRole: 'KADIN_ADMIN',
    category: 'Finansial',
    title: 'Informasi Penyaluran KUR Super Mikro & Mikro Kuartal IV 2026',
    content: 'Bagi rekan-rekan pelaku UMKM yang membutuhkan injeksi modal kerja menjelang akhir tahun, alokasi KUR perbankan mitra pemerintah saat ini masih terbuka lebar dengan subsidi bunga 6%. Pastikan NIB dan pembukuan sederhana Anda telah siap.',
    likesCount: 92,
    commentsCount: 31,
    isLiked: true,
    isBookmarked: true,
    createdAt: '2026-09-05T11:00:00Z',
    tags: ['KUR', 'Permodalan', 'KADIN', 'Finansial'],
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prd-01',
    sellerId: 'biz-001',
    businessName: 'Sambal Roa Kencana Nusantara',
    name: 'Sambal Roa Asap Khas Manado Botol Kaca 150g',
    category: 'Kuliner',
    price: 38000,
    minOrder: 1,
    stock: 240,
    rating: 4.9,
    reviewsCount: 128,
    location: 'Kota Bekasi, Jawa Barat',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
    description: 'Ikan roa asap asli didatangkan langsung dari perairan Manado, diolah dengan minyak kelapa murni dan cabai rawit segar. Tanpa pengawet buatan, bersertifikat Halal & P-IRT.',
    halalCertified: true,
    b2bReady: true,
    exportReady: true,
  },
  {
    id: 'prd-02',
    sellerId: 'biz-002',
    businessName: 'Kopi Robusta Lereng Gunung Lawu',
    name: 'Kopi Robusta Fine Natural Roast Beans 250g',
    category: 'Kuliner',
    price: 45000,
    minOrder: 2,
    stock: 150,
    rating: 4.8,
    reviewsCount: 89,
    location: 'Kabupaten Karanganyar, Jawa Tengah',
    image: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=600&auto=format&fit=crop&q=80',
    description: 'Biji kopi robusta pilihan dari perkebunan lereng Lawu ketinggian 800 mdpl. Profil sangrai medium-dark dengan notes dark chocolate dan karamel tebal.',
    halalCertified: true,
    b2bReady: true,
    exportReady: true,
  },
  {
    id: 'prd-03',
    sellerId: 'biz-003',
    businessName: 'Tenun Sutera Etnik Mandar',
    name: 'Kain Tenun Sutera Sutera Tradisional Etnik Pesisir',
    category: 'Fashion',
    price: 285000,
    minOrder: 1,
    stock: 45,
    rating: 5.0,
    reviewsCount: 42,
    location: 'Polewali Mandar, Sulawesi Barat',
    image: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=600&auto=format&fit=crop&q=80',
    description: 'Ditenun manual menggunakan Alat Tenun Bukan Mesin (ATBM) dengan benang sutera alam dan pewarna nabati ramah lingkungan. Cocok untuk busana formal dan cendera mata diplomatik.',
    halalCertified: false,
    b2bReady: true,
    exportReady: true,
  },
  {
    id: 'prd-04',
    sellerId: 'biz-004',
    businessName: 'Anyaman Bambu Lestari Parahyangan',
    name: 'Paket Hamper Keranjang Anyaman Bambu Eksklusif',
    category: 'Kerajinan',
    price: 75000,
    minOrder: 10,
    stock: 300,
    rating: 4.7,
    reviewsCount: 67,
    location: 'Kabupaten Tasikmalaya, Jawa Barat',
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80',
    description: 'Anyaman bambu halus dengan lapisan anti jamur alami. Pilihan utama untuk packaging hampers Lebaran, seminar kit, dan suvenir korporasi.',
    halalCertified: false,
    b2bReady: true,
    exportReady: false,
  },
];

export const INITIAL_MENTORS: Mentor[] = [
  {
    id: 'mnt-01',
    name: 'Drs. Taufik Hidayat, M.B.A.',
    headline: 'Senior Mentor Scale-up Bisnis Kuliner & Retail',
    company: 'Eks Direktur Operasional Foodindo & Komite UMKM KADIN',
    industry: ['Kuliner', 'Retail', 'Manufaktur'],
    expertise: ['Standarisasi SOP', 'Strategi Pertumbuhan', 'Penyusunan HPP', 'Distribusi Nasional'],
    rating: 4.95,
    sessionsCompleted: 142,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
    availability: 'Tersedia Pekan Ini',
    bio: 'Lebih dari 20 tahun mendampingi brand kuliner Nusantara dari skala dapur rumahan hingga memiliki jaringan distributor di 24 kota besar.',
  },
  {
    id: 'mnt-02',
    name: 'Maya Puspitasari, S.Sos.',
    headline: 'Pakar Pemasaran Digital & Social Commerce',
    company: 'Founder GrowMedia & Instruktur GoodSkill',
    industry: ['Digital', 'Fashion', 'Beauty', 'Kuliner'],
    expertise: ['TikTok Shop & Live Selling', 'Optimasi Iklan Meta Ads', 'Branding & Packaging'],
    rating: 4.9,
    sessionsCompleted: 188,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    availability: 'Tersedia Pekan Ini',
    bio: 'Fokus membantu UMKM mengonversi penonton media sosial menjadi pembeli loyal dengan budget pemasaran yang efisien dan terukur.',
  },
  {
    id: 'mnt-03',
    name: 'Kurniawan Santosa, S.T., M.Sc.',
    headline: 'Konsultan Ekspor & Kepatuhan Standar Global',
    company: 'Export Coach Indonesia & Asosiasi Logistik',
    industry: ['Pertanian', 'Kerajinan', 'Fashion', 'Kuliner'],
    expertise: ['Negosiasi Buyer Asing', 'Sertifikasi ISO/HACCP', 'Penetapan Harga Ekspor', 'Incoterms'],
    rating: 4.88,
    sessionsCompleted: 95,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    availability: 'Sesuai Janji',
    bio: 'Berpengalaman memfasilitasi lebih dari 60 kontainer produk UMKM Indonesia masuk ke pasar Jepang, Australia, dan Timur Tengah.',
  },
];

export const INITIAL_PROGRAMS: ProgramOpportunity[] = [
  {
    id: 'prg-01',
    title: 'Fasilitasi Sertifikasi Halal Gratis (SEHATI) 2026',
    organizer: 'Kementerian Koperasi & UKM',
    type: 'Sertifikasi Halal',
    targetCategory: 'Kuliner',
    quota: 5000,
    registeredCount: 3820,
    deadline: '31 Oktober 2026',
    status: 'Buka Pendaftaran',
    description: 'Program percepatan kepemilikan sertifikasi halal bagi UMKM makanan & minuman melalui skema self-declare dengan pendampingan gratis sampai terbit sertifikat BPJPH.',
    benefits: [
      'Biaya sertifikasi 100% ditanggung pemerintah',
      'Pendampingan langsung oleh Pendamping Proses Produk Halal (P3H)',
      'Akses prioritas katalog belanja pemerintah (e-Katalog LKPP)',
    ],
    eligibility: [
      'Memiliki Nomor Induk Berusaha (NIB) berbasis risiko',
      'Produk tidak menggunakan bahan berisiko tinggi (daging sembelihan tanpa sertifikat halal)',
      'Proses pengolahan sederhana dan higienis',
    ],
  },
  {
    id: 'prg-02',
    title: 'KADIN Business Matching: Suplai Rantai Pasok BUMN & Perhotelan',
    organizer: 'KADIN Indonesia',
    type: 'Business Matching',
    targetCategory: 'Semua Sektor',
    quota: 250,
    registeredCount: 184,
    deadline: '15 November 2026',
    status: 'Buka Pendaftaran',
    description: 'Temu bisnis langsung antara pelaku UMKM terkurasi dengan Procurement Manager jaringan BUMN, hotel nasional, dan retail modern.',
    benefits: [
      'Peluang kontrak pasokan rutin jangka panjang',
      'Kurasi langsung oleh tim pengadaan korporasi',
      'Fasilitasi pembiayaan PO Financing dari Bank Mitra',
    ],
    eligibility: [
      'Usaha telah berjalan minimal 1 tahun',
      'Kapasitas produksi stabil dan mampu memenuhi minimum order kuantitas',
      'Skor Pertumbuhan Usaha (Growth Score) minimal 65',
    ],
  },
  {
    id: 'prg-03',
    title: 'Inkubasi & Kurasi UMKM Go Export ASEAN & Middle East',
    organizer: 'KADIN Indonesia',
    type: 'Go Export',
    targetCategory: 'Semua Sektor',
    quota: 100,
    registeredCount: 76,
    deadline: '20 Desember 2026',
    status: 'Buka Pendaftaran',
    description: 'Akselerasi kesiapan ekspor mencakup uji laboratorium nutrisi, redesain kemasan dwibahasa, dan partisipasi pada pameran dagang internasional.',
    benefits: [
      'Subsidi biaya kurasi & uji mutu produk ekspor',
      'Booth pameran dagang Trade Expo Indonesia',
      'One-on-one pitching dengan buyer diaspora',
    ],
    eligibility: [
      'Produk memiliki legalitas lengkap (NIB, Halal/BPOM/HAKI)',
      'Memiliki komitmen peningkatan kapasitas produksi',
      'Kesiapan ekspor berada di level Potensi Ekspor atau Siap Ekspor',
    ],
  },
];

export const REGIONAL_STATISTICS = {
  national: {
    totalUmkm: 124850,
    activeUmkm: 98420,
    certifiedUmkm: 41200,
    totalGmv: 'Rp 48.6 Miliar',
    coursesCompleted: 86400,
    mentoringSessions: 14500,
  },
  provinces: [
    { name: 'Jawa Barat', total: 32450, active: 26100, verified: 12800, gmv: 'Rp 14.2 M' },
    { name: 'DKI Jakarta', total: 28120, active: 23400, verified: 11900, gmv: 'Rp 16.5 M' },
    { name: 'Jawa Timur', total: 22400, active: 17800, verified: 8100, gmv: 'Rp 7.8 M' },
    { name: 'Jawa Tengah', total: 18900, active: 14600, verified: 6200, gmv: 'Rp 5.4 M' },
    { name: 'Banten', total: 9800, active: 7500, verified: 3400, gmv: 'Rp 3.1 M' },
    { name: 'Sulawesi Selatan', total: 6400, active: 4800, verified: 2100, gmv: 'Rp 1.9 M' },
    { name: 'Sumatera Utara', total: 6780, active: 4220, verified: 1900, gmv: 'Rp 1.7 M' },
  ],
};
